// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import model_2 from 'C:/Users/ZTS/Desktop/dev/timo/src/.umi/plugin-initialState/@@initialState';
import model_1 from 'C:/Users/ZTS/Desktop/dev/timo/src/models/global';

export const models = {
model_2: { namespace: '@@initialState', model: model_2 },
model_1: { namespace: 'global', model: model_1 },
} as const
